### ISSUE TITLE
No result for score lower than 0.5

### ISSUE THREAD

**Issue by brabbitlee** [xdever/RFCN-tensorflow#4] opened 2017-05-15 06:38 UTC
Hi, I set the test threshold to 0.01, but there're only bounding boxes with scores higher than 0.5. Can I get results with scores lower than 0.5?
Thank you so much.

**Comment by RobertCsordas** [comment] 2017-05-15 06:45
Hi, this is probably a duplicate of #2.

**Closed as completed** 2017-05-24 20:09 UTC
